import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import { Navbar } from "@/components/layout/navbar";
import "./globals.css";

const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${cairo.variable} antialiased font-sans`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
